#!/bin/sh
is_xrdp() {
  [ -z "$DISPLAY" ] && return 1
  local port=$(echo $DISPLAY | cut -d . -f1 | tr -d :)
  local xorgpid=$(ss -lxp | awk '$5 == "/tmp/.X11-unix/X'"$port"'" {
      if (match($0, /,pid=([0-9]+)/,arr)) {
        print arr[1];
      }
    }')
  [ -z "$xorgpid" ]  && return 1
  local sesspid=$(awk '$1 == "PPid:" { print $2 }' /proc/$xorgpid/status)
  [ -z "$sesspid" ] && return 1
  local name=$(awk '$1 == "Name:" { print $2 }' /proc/$sesspid/status)
  if [ x"$name" = x"xrdp-sesman" ] ; then
    return 0
  fi
  return 1
}

IS_VIRTUAL=false
if (xdpyinfo | grep -q XVNC-EXTENSION) ; then
  IS_VIRTUAL=true
elif is_xrdp ; then
  IS_VIRTUAL=true
fi


# Make sure this fonts are included...
[ -d /usr/share/fonts/TTF ] && xset fp+ /usr/share/fonts/TTF
[ -f $HOME/.Xdefaults ] && xrdb -merge $HOME/.Xdefaults

#
# Other stuff moved to $HOME/.bin/autostart.sh
#

# Configure keyboard... this is more suitable for programming
$IS_VIRTUAL || setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl
# Enable Shift-NumLock to toggle mouse control to the keyboard number pad
$IS_VIRTUAL || setxkbmap -option keypad:pointerkeys

#geany &
#exec > /tmp/errors.log 2>&1

#xbindkeys &
#(
#  sleep 500
#  xset dpms 1800 3600 7200
#  xset +dpms
#) &
