#!/bin/sh
#
# This is run by the /etc/X11/xinit/session or /etc/X11/xdm/Xsession
# scripts early in the process.  Before the Desktop Environment
# is present.
#

export HK_HELPER_SAVE_SCREENSHOT_FILE=1

is_xrdp() {
  [ -z "$DISPLAY" ] && return 1
  local port=$(echo $DISPLAY | cut -d . -f1 | tr -d :)
  local xorgpid=$(ss -lxp | awk '$5 == "/tmp/.X11-unix/X'"$port"'" {
      if (match($0, /,pid=([0-9]+)/,arr)) {
        print arr[1];
      }
    }')
  [ -z "$xorgpid" ]  && return 1
  local sesspid=$(awk '$1 == "PPid:" { print $2 }' /proc/$xorgpid/status)
  [ -z "$sesspid" ] && return 1
  local name=$(awk '$1 == "Name:" { print $2 }' /proc/$sesspid/status)
  if [ x"$name" = x"xrdp-sesman" ] ; then
    return 0
  fi
  return 1
}

IS_VIRTUAL=false
if (xdpyinfo | grep -q XVNC-EXTENSION) ; then
  IS_VIRTUAL=true
elif is_xrdp ; then
  IS_VIRTUAL=true
fi
export IS_VIRTUAL

# Make sure this fonts are included...
[ -d /usr/share/fonts/TTF ] && xset fp+ /usr/share/fonts/TTF
[ -f $HOME/.Xdefaults ] && xrdb -merge $HOME/.Xdefaults

if ! $IS_VIRTUAL ; then
  # Configure keyboard... this is more suitable for programming
  setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl
  # Enable Shift-NumLock to toggle mouse control to the keyboard number pad
  setxkbmap -option keypad:pointerkeys

  # Make sure NUMLOCK is on
  case "$(uname -n)" in
    *) numlockx on ;;
  esac
  #(
  #  sleep 500
  #  xset dpms 1800 3600 7200
  #  xset +dpms
  #) &
fi

