#!/usr/bin/php 
<?php
require_once(realpath(dirname(__FILE__)).'/parsedown/Parsedown.php');

$verbose = 0;
$view = 0;

array_shift($argv);	# Skip cmd name

while (count($argv) > 0) {
  if ($argv[0] == "--view") {
    $view = 1;
  } else if ($argv[0] == "-v" || $argv[0] == "--verbose") {
    $verbose=1;
  } else if ($argv[0] == "-q" || $argv[0] == "--quiet") {
    $verbose=0;
  } else {
    break;
  }
  array_shift($argv);
}

function fileroot($filepath)
{
  $bname=basename($filepath);
  $pos = strrpos($bname,".");
  if ($pos) {
    $bname = substr($bname,0,$pos);
    # echo "$filepath - $pos $bname\n";
  }
  return dirname($filepath)."/".$bname;
}

function Markdown($txt) {
  $Parsedown = new Parsedown();
  return $Parsedown->text($txt);
}

if (count($argv) == 0) {
  $txt = file_get_contents("php://stdin");
  $html = Markdown($txt);
  print $html;
} else {
  if ($verbose) {
    $STDERR = fopen("php://stderr","w");
  }
  foreach ($argv as $file) {
    $txt = file_get_contents($file);
    $html = Markdown($txt);
    $target = fileroot($file).".html";
    if ($verbose) {
      fwrite($STDERR,"Converting $file to ".basename($target)."\n");
    }
    file_put_contents($target,$html);
    if ($view) {
       system("xdg-open $target");
    }
  }
}
