#!/bin/sh
eval $(ashlib)
pkgdir=$(dirname $ASHLIB)
phpdoctor_dir=$pkgdir/phpdoctor
myphpdoc_dir=$pkgdir/myphpdoc
tmpini=$(mktemp)
trap "rm -f $tmpini" EXIT

DEFS=()

while [ $# -gt 0 ] ; do
  if [ x$(expr substr "$1" 1 2) = x"-D" ] ; then
    DEFS+=("${1#-D}")
    shift
  else
    break
  fi
done



if [ $# -eq 0 ] ; then
  if [ -f $(pwd)/phpdoctor.ini ] ; then
    set - $(pwd)/phpdoctor.ini
  elif [ -n "$PHPDoctor" ] ; then
    set - "$PHPDoctor"
  else
    fatal "Usage: $(basename $0) [config_file ...]"
  fi
fi

php_code=""
php_code="$php_code;define('PHPDOCTOR_DIR','$phpdoctor_dir');"
php_code="$php_code;define('MYPHPDOC_DIR','$phpdoctor_dir');"
for cfgin in "${@}"
do
  php_code="$php_code;require_once('$cfgin');"
done
(
  php -r "$php_code" -- "$@"
  if [ -n "${DEFS[*]}" ] ; then
    for x in "${DEFS[@]}"
    do
      echo $x
    done
  fi
)> $tmpini


php_code=""
php_code="$php_code;require_once('$pkgdir/php-markdown/Michelf/Markdown.inc.php');"
php_code="$php_code;require_once('$phpdoctor_dir/phpdoc.php');"
php -r "$php_code" -- $tmpini "$@"
