#!/bin/sh
#
# Bash stuff
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

alias more=less
alias moer=less
alias mroe=less

alias emacs="cmd //c runemacs.bat"
