#!/bin/sh
#
# Used to convert geany repository into geany.conf
#
exec 1>&2
(
  # Used to convert session.conf into session.git
  cd config/geany || exit 1
  ./prepare extract session.conf session.git
)
