#!/usr/bin/env php
<?php
if (count($argv)) $cmd = array_shift($argv);

if (!count($argv)) die("Must specify a .phar file\n");
$phar_file=array_shift($argv);
if (!is_readable($phar_file)) die("Unable to open: $phar_file\n");

$phar = new Phar($phar_file);

$target_path='.';
if (count($argv)) {
  $target_path = array_shift($argv);
  if (!is_dir($target_path)) {
    mkdir($target_path) || die("Unable to extract to $target_path\n");
  }
}

if (count($argv)) {
  foreach ($argv as $f) {
    $phar->extractTo($target_path,$f);
  }
} else {
  $phar->extractTo($target_path);
}